function Cable = UpdateModelVectors_dpose(Cable,UACDPR)

    Cable.ModelVectors_dpose.ap= permute(...
            (matrixwrtvector_matrix(UACDPR.EndEffector.RotMatrix_dpose,UACDPR.EndEffector.Platform_Param.AttachPoint{Cable.Id})),...
            [1 3 2]);       %         ap{i}_dpose = tensorprod(UACDPR.EndEffector.RotMatrix_dpose,LocalAttachPoints{Cable.Id},2,1);

    Cable.ModelVectors_dpose.varrho= [eye(3) zeros(3)] + Cable.ModelVectors_dpose.ap;

    Cable.ModelVectors_dpose.varrho_u= matrixwrtvector_matrix(permute(Cable.ModelVectors_dpose.varrho,[3 1 2]),...
        UACDPR.Trasmission.Pulley{Cable.Id}.PulleyFrame{1}) + ...
        matrix_matrixwrtvector(Cable.ModelVectors.varrho',...
        permute(UACDPR.Trasmission.Pulley{Cable.Id}.PulleyFrame_dpose{1},[1 3 2]));

    Cable.ModelVectors_dpose.rho= UACDPR.Trasmission.Pulley{Cable.Id}.CableFrame{1}* ...
        (Cable.Length_dpose + UACDPR.Trasmission.Pulley{Cable.Id}.Radius*UACDPR.Trasmission.Pulley{Cable.Id}.TangencyAngle_dpose) + ...
        UACDPR.Trasmission.Pulley{Cable.Id}.CableFrame_dpose{1}*...
        (Cable.Length - UACDPR.Trasmission.Pulley{Cable.Id}.Radius*(pi - UACDPR.Trasmission.Pulley{Cable.Id}.TangencyAngle));

    Cable.ModelVectors_dpose.norm_rho= 1/norm(Cable.ModelVectors.rho) *...
        Cable.ModelVectors.rho'*Cable.ModelVectors_dpose.rho;

    Cable.ModelVectors_dpose.inv_norm_rho= -1/(norm(Cable.ModelVectors.rho)^2) *Cable.ModelVectors_dpose.norm_rho;
end